FROM tomcat:jdk8-openjdk-slim

ENV TIMEZONE="America/New_York"
ENV XMS=2g XMX=4g BANNERDB_JDBC=jdbc:oracle:thin:@//oracle.example.edu:1521/prod \
  BANPROXY_USERNAME=banproxy \
  BANPROXY_INITALSIZE=25 \
  BANPROXY_MAXTOTAL=400 \
  BANPROXY_MAXACTIVE=300 \
  BANPROXY_MAXIDLE=-1 \
  BANPROXY_MAXWAIT=30000 \
  BANSSUSER_USERNAME=ban_ss_user \
  BANSSUSER_INITALSIZE=25 \
  BANSSUSER_MAXTOTAL=400 \
  BANSSUSER_MAXACTIVE=300 \
  BANSSUSER_MAXIDLE=-1 \
  BANSSUSER_MAXWAIT=30000 \
  REMOVE_ABANDONED_ON_MAINTENANCE=true \
  REMOVE_ABANDONED_ON_BORROW=true \
  REMOVE_ABANDONED_TIMEOUT=2100 \
  LOG_ABANDONED=true \
  DEFAULT_ROW_PREFETCH=150 \
  JMX_EXPORTER_CONFIG=/usr/local/tomcat/conf/tomcat_jmx_exporter.yaml

ENV CATALINA_OPTS="-server -Xms\$XMS -Xmx\$XMX -Duser.timezone=\$TIMEZONE -Doracle.jdbc.autoCommitSpecCompliant=false"

RUN apt-get update \
    && rm -Rf /usr/local/tomcat/webapps/* \
    && apt-get install -y tzdata xmlstarlet curl \
    && rm -rf /var/cache/apt/archives \
    && cp /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
    && adduser --system --group --home /usr/local/tomcat tomcat

ADD https://maven.xwiki.org/externals/com/oracle/jdbc/ojdbc8/12.2.0.1/ojdbc8-12.2.0.1.jar /usr/local/tomcat/lib/ojdbc8.jar
ADD https://ci.cimm2.com/artifactory/libs-release-local/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.jar /usr/local/tomcat/lib/ucp.jar
ADD https://developer.byu.edu/maven2/content/groups/thirdparty/com/oracle/xdb6/12.1.0.2/xdb6-12.1.0.2.jar /usr/local/tomcat/lib/xdb6.jar
ADD https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar /usr/local/tomcat/lib/jmx_exporter.jar

RUN cd /usr/local/tomcat/lib/ \
  && curl https://maven.xwiki.org/externals/com/oracle/jdbc/ojdbc8/12.2.0.1/ojdbc8-12.2.0.1.jar.sha1 --output ojdbc8.jar.sha1 \
  && echo -n "  ojdbc8.jar" >> ojdbc8.jar.sha1 \
  && sha1sum -c ojdbc8.jar.sha1 \
  && curl https://ci.cimm2.com/artifactory/libs-release-local/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.jar.sha1 --output ucp.jar.sha1 \
  && echo -n "  ucp.jar" >> ucp.jar.sha1 \
  && sha1sum -c ucp.jar.sha1 \
  && curl https://developer.byu.edu/maven2/content/groups/thirdparty/com/oracle/xdb6/12.1.0.2/xdb6-12.1.0.2.jar.sha1 --output xdb6.jar.sha1 \
  && echo -n "  xdb6.jar" >> xdb6.jar.sha1 \
  && sha1sum -c xdb6.jar.sha1 \
  && curl https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar.sha1 --output jmx_exporter.jar.sha1 \
  && echo -n "  jmx_exporter.jar" >> jmx_exporter.jar.sha1 \
  && sha1sum -c jmx_exporter.jar.sha1 \
  && rm *.sha1 \
  && chown tomcat:tomcat ojdbc8.jar xdb6.jar ucp.jar \
  && chmod +r ojdbc8.jar xdb6.jar ucp.jar

COPY context.xml /usr/local/tomcat/conf/context.xml
COPY server.xml /usr/local/tomcat/conf/server.xml
COPY tomcat_jmx_exporter.yaml /usr/local/tomcat/conf/tomcat_jmx_exporter.yaml
COPY run.sh /usr/local/tomcat/bin

# Configure logging to forward tomcat logs to docker log collector
COPY logging.properties /usr/local/tomcat/conf/logging.properties
RUN ln -s /dev/stderr /usr/local/tomcat/logs/localhost.log \
    && ln -s /dev/stderr /usr/local/tomcat/logs/stacktrace.log \
    && mkdir -p /opt/banner/config \
    && mkdir -p /opt/banner/images \
    && chown -R tomcat:tomcat /opt/banner \
    && chown -R tomcat:tomcat /usr/local/tomcat \
    && chmod +x /usr/local/tomcat/bin/run.sh

EXPOSE 8080
USER tomcat
CMD ["bin/run.sh"]
